# Generated by Django 3.1.7 on 2021-03-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('ingredients', models.TextField(max_length=1000)),
                ('method', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='static/img/')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
