# Generated by Django 3.1.7 on 2021-04-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210401_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='name',
            new_name='category',
        ),
    ]
